=== yanbenjun/study/src/main/resources/fileParse.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fileParse (parseSystem*)>
<!ELEMENT parseSystem (toParseFile*)>
<!ELEMENT toParseFile (toParseTemplate+)>
<!ELEMENT toParseTemplate (columnHead*)>
<!ELEMENT columnHead (#PCDATA)>
<!ELEMENT convertor (#PCDATA)>

<!ATTLIST parseSystem name ID #REQUIRED>
<!ATTLIST toParseFile name CDATA #REQUIRED>
<!ATTLIST toParseTemplate index CDATA #REQUIRED>
<!ATTLIST toParseTemplate priority CDATA #IMPLIED>
<!ATTLIST columnHead titleName CDATA #REQUIRED>
<!ATTLIST columnHead fieldName CDATA #REQUIRED>
<!ATTLIST columnHead required (true|false) #IMPLIED>
<!ATTLIST columnHead type (integer|CDATA) #IMPLIED>
<!ATTLIST columnHead horizontalMerger (integeradd|CDATA) #IMPLIED>

<!ENTITY copyright SYSTEM "http://www.baidu.com">

=== yanbenjun/study/src/main/resources/fileParse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fileParse SYSTEM "fileParse.dtd">
<fileParse>
	<parseSystem name="test">
		<toParseFile name="test">
			<toParseTemplate index="0" priority="0">
				<columnHead titleName="序号" fieldName="index" required="true"/>
				<columnHead titleName="关键字" fieldName="key" required="true"/>
				<columnHead titleName="名称" fieldName="name"/>
				<columnHead titleName="经度" fieldName="lng" type="integer" horizontalMerger="integeradd"/>
				<columnHead titleName="纬度" fieldName="lat"/>
			</toParseTemplate>
			<toParseTemplate index="1">
				<columnHead titleName="" fieldName="">
				</columnHead>
			</toParseTemplate>
		</toParseFile>
	</parseSystem>
</fileParse>
