=== yanbenjun/study/src/main/resources/fileParse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.yanbenjun.com" xmlns:xns="http://www.yanbenjun.com"
	elementFormDefault="qualified">

	<xs:attributeGroup name="templateMappingAttrGroup">
		<!-- 采用此属性，表示按照该模板解析到该模型Class中，生成该模型的对象 -->
		<xs:attribute name="modelClass" type="xs:string" use="optional"></xs:attribute>

		<!-- typeEnum和type应当合起来使用，采用这两个属性，使用typeEnum指定的枚举类中，id为type的枚举对应的处理器处理，此处应当用map数据作为处理器的入口数据 -->
		<xs:attribute name="typeEnum" type="xs:string" use="optional"></xs:attribute>
		<xs:attribute name="type" type="xs:unsignedInt" use="optional"></xs:attribute>

		<!-- 自定义处理器 -->
		<xs:attribute name="userDefined" type="xs:string" use="optional"></xs:attribute>
	</xs:attributeGroup>

	<xs:element name="fileParse">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="xns:parseSystem"></xs:element>
			</xs:sequence>
		</xs:complexType>

		<!-- 不同解析系统名称不能相同 -->
		<xs:unique name="parseSystemNameUnique">
			<xs:selector xpath=".//xns:parseSystem"></xs:selector>
			<xs:field xpath="@name"></xs:field>
		</xs:unique>
	</xs:element>
	
	<!-- parseSystem可选元素 -->
	<xs:group name="systemChoosableElementsGroup">
	    <xs:choice>
            <xs:element ref="xns:toParseFile" maxOccurs="unbounded"></xs:element>
            <xs:element ref="xns:templates" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="xns:columns" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="xns:files" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:choice>
	</xs:group>
	
	<xs:element name="files">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="xns:toParseFile"></xs:element>
            </xs:sequence>
            <xs:attribute name="sort" fixed="3" type="xs:string"></xs:attribute>
        </xs:complexType>
    </xs:element>
	
	<xs:element name="templates">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="xns:toParseTemplate"></xs:element>
            </xs:sequence>
            <xs:attribute name="sort" fixed="2" type="xs:string"></xs:attribute>
        </xs:complexType>
    </xs:element>
    
	<xs:element name="columns">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="xns:columnHead"></xs:element>
            </xs:sequence>
            <xs:attribute name="sort" fixed="1" type="xs:string"></xs:attribute>
        </xs:complexType>
    </xs:element>

	<xs:element name="parseSystem">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:group ref="xns:systemChoosableElementsGroup" minOccurs="1" maxOccurs="1"></xs:group>
				<xs:element ref="xns:parsePoint" maxOccurs="unbounded"></xs:element>
			</xs:choice>

			<!-- 解析系统唯一名称 -->
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>

		<xs:key name="fileKey">
			<xs:selector xpath="xns:files/xns:toParseFile"></xs:selector>
			<xs:field xpath="@name"></xs:field>
		</xs:key>
		<xs:keyref name="fileKeyRef" refer="xns:fileKey">
			<xs:selector xpath=".//xns:refFile"></xs:selector>
			<xs:field xpath="@name"></xs:field>
		</xs:keyref>
		      
        <xs:key name="templateKey">
            <xs:selector xpath="xns:templates/xns:toParseTemplate"></xs:selector>
            <xs:field xpath="@name"></xs:field>
        </xs:key>
        <xs:keyref name="templateKeyref" refer="xns:templateKey">
            <xs:selector xpath=".//xns:refTemplate"></xs:selector>
            <xs:field xpath="@name"></xs:field>
        </xs:keyref>
        
        <xs:key name="columnHeadIdKey2">
            <xs:selector xpath="xns:columns/xns:columnHead"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:key>
        <xs:keyref name="columnHeadIdKeyref2" refer="xns:columnHeadIdKey2">
            <xs:selector xpath=".//xns:refColumn"></xs:selector>
            <xs:field xpath="@id"></xs:field>
        </xs:keyref>
	</xs:element>

	<xs:element name="parsePoint">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="xns:toParseFile" maxOccurs="unbounded"></xs:element>
				<xs:element ref="xns:refFile" maxOccurs="unbounded"></xs:element>
			</xs:choice>

			<!-- 解析点唯一ID -->
			<xs:attribute name="id" type="xs:unsignedLong" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="toParseFile">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="xns:toParseTemplate"></xs:element>
				<!-- <xs:element name="refTemplate">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attributeGroup ref="xns:templateMappingAttrGroup"></xs:attributeGroup>
					</xs:complexType>
				</xs:element> -->
				<xs:element ref="xns:refTemplate"></xs:element>
			</xs:choice>
			<!-- 解析文件唯一名称 -->
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="mode" default="single" use="optional">
			    <xs:simpleType>
			        <xs:restriction base="xs:string">
			            <xs:enumeration value="single"></xs:enumeration>
			            <xs:enumeration value="multi"></xs:enumeration>
			        </xs:restriction>
			    </xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="refFile">
		<xs:complexType>
			<!-- 此处一定要加type类型，不然keyref限制时，再使用时会报错 -->
			<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="toParseTemplate">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="xns:columnHead" maxOccurs="unbounded"></xs:element>
				<xs:element ref="xns:refColumn" maxOccurs="unbounded"></xs:element>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="optional"/>
			<xs:attribute name="sheetIndex" type="xs:unsignedInt" use="required"></xs:attribute>
			<xs:attribute name="headRow" type="xs:unsignedInt"
				default="0"></xs:attribute>
			<xs:attribute name="contentStartRow" type="xs:positiveInteger"
				default="1"></xs:attribute>

			<xs:attributeGroup ref="xns:templateMappingAttrGroup"></xs:attributeGroup>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="refTemplate">
        <xs:complexType>
            <!-- 此处一定要加type类型，不然keyref限制时，再使用时会报错 -->
            <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
            <xs:attribute name="sheetIndex" type="xs:unsignedInt" use="optional"></xs:attribute>
            <xs:attributeGroup ref="xns:templateMappingAttrGroup"></xs:attributeGroup>
        </xs:complexType>
    </xs:element>

	<xs:element name="columnHead">
		<xs:complexType>
			<xs:attributeGroup ref="xns:columnAttrGroup" />
		</xs:complexType>
	</xs:element>
	
	   
    <xs:element name="refColumn">
        <xs:complexType>
            <!-- 此处一定要加type类型，不然keyref限制时，再使用时会报错 -->
            <xs:attribute name="id" type="xs:string" use="required">
            </xs:attribute>
        </xs:complexType>
    </xs:element>
	
    <xs:attributeGroup name="columnAttrGroup">
        <xs:attribute name="id" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="ref" type="xs:string" use="optional"></xs:attribute>
        <xs:attribute name="titleName" type="xs:string"></xs:attribute>
        <xs:attribute name="fieldName" type="xs:string"></xs:attribute>
        <xs:attribute name="required" type="xs:boolean" default="false"></xs:attribute>
        <xs:attribute name="type" type="xs:string" default="string"></xs:attribute>
        <xs:attribute name="horizontalMerger" type="xs:string"></xs:attribute>
        <xs:attribute name="xmlExtendInfo" type="xs:string"></xs:attribute>
    </xs:attributeGroup>
</xs:schema>

=== yanbenjun/study/src/main/resources/fileParse-context.xml
<?xml version="1.0" encoding="UTF-8"?>

<fileParse xmlns="http://www.yanbenjun.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.yanbenjun.com fileParse.xsd">
    <!-- 
        *解析系统，集成到业务系统中，让业务系统能够方便的让开发整合excel、csv、xml数据解析功能到业务系统；
        *可以灵活的配置不同的模板、或者竟可能多的包络系统已知属性，形成一个通用模板；
        *具体用什么model装数据、存储到什么数据库、可以配置到xml里写死（适合固定模板的解析）；也可以不用配置，等用户上传
        *完文件后，让用户确认文件类型或者将类型写入到Excel自动识别（和业务有关），类型可以知道数据存储的java模型和具体入库
        *数据库。
     -->
	<parseSystem name="test">
		<!-- 通用列配置 -->
		<columns>
			<columnHead id="1" titleName="序号" fieldName="index"
				required="true" type="integer" />
			<columnHead id="2" titleName="关键字" fieldName="key"
				required="true" type="string" />
			<columnHead id="3" titleName="名称" fieldName="name" type="string" />
			<columnHead id="4" titleName="经度" fieldName="lng" type="double" />
			<columnHead id="5" titleName="纬度" fieldName="lat" type="double" horizontalMerger="doubleadd"/>
		</columns>

		<!-- 通用sheet模板配置 -->
		<templates>
			<toParseTemplate name="myTemplate" sheetIndex="1">
				<columnHead titleName="序号" fieldName="index" required="true"
					type="integer" />
				<columnHead titleName="名称" fieldName="name" required="true"
					type="string" />
				<columnHead titleName="分类" fieldName="category" required="true"
					type="string" />
				<columnHead titleName="所属技术类" fieldName="techonology"
					type="string" />
				<columnHead titleName="是否掌握" fieldName="grasp" type="boolean" />
			</toParseTemplate>
			<toParseTemplate name="testTemplate" sheetIndex="1">
				<refColumn id="1" />
				<refColumn id="2" />
				<refColumn id="3" />
				<refColumn id="4" />
				<refColumn id="5" />
			</toParseTemplate>
		</templates>

		<!-- 通用解析文件配置 -->
		<files>
			<toParseFile name="myTestFile" mode="single">
				<refTemplate name="myTemplate" />
			</toParseFile>
		</files>

        <!-- 解析点，具体的业务系统，哪里需要解析文件，只需要在请求中传入该解析点ID，就可以自动根据解析点的配置，自动解析入库 -->
		<parsePoint id="20180715">
			<toParseFile name="test" mode="multi">
				<toParseTemplate sheetIndex="0">
					<refColumn id="1" />
					<refColumn id="2" />
					<refColumn id="3" />
					<refColumn id="4" />
					<refColumn id="5" />
				</toParseTemplate>
				<toParseTemplate sheetIndex="1" headRow="0" contentStartRow="1">
					<columnHead titleName="序号" fieldName="index" required="true"
						type="string" />
					<columnHead titleName="名称" fieldName="name" required="true"
						type="string" />
					<columnHead titleName="分类" fieldName="category"
						required="true" type="string" />
					<columnHead titleName="所属技术类" fieldName="techonology"
						type="string" />
					<columnHead titleName="是否掌握" fieldName="grasp" type="boolean" />
				</toParseTemplate>
				<toParseTemplate sheetIndex="1">
					<refColumn id="1" />
					<refColumn id="3" />
					<columnHead titleName="分类" fieldName="category"
						required="true" type="string" />
					<columnHead titleName="所属技术类" fieldName="techonology"
						type="string" />
					<columnHead titleName="是否掌握" fieldName="grasp" type="boolean" />
				</toParseTemplate>
				<refTemplate name="myTemplate" sheetIndex="2" />
			</toParseFile>
			<refFile name="myTestFile"/>
		</parsePoint>
		
		<!-- 解析点，具体的业务系统，哪里需要解析文件，只需要在请求中传入该解析点ID，就可以自动根据解析点的配置，自动解析入库 -->
        <parsePoint id="20180916">
            <toParseFile name="test" mode="single">
                <toParseTemplate sheetIndex="0" headRow="0" contentStartRow="1">
                    <columnHead titleName="ASDL" fieldName="ASDL" required="true"
                        type="string" xmlExtendInfo='{"xmlPath":{"path":["simpleData"]},"pathDirect":1,"keyPath":2,"valuePath":3,"attrName":"name","attrValue":"ASDL"}'/>
                    <columnHead titleName="HTTP" fieldName="HTTP" required="true"
                        type="string" xmlExtendInfo='{"xmlPath":{"path":["simpleData"]},"pathDirect":1,"keyPath":2,"valuePath":3,"attrName":"name","attrValue":"HTTP"}'/>
                    <columnHead titleName="age" fieldName="age" required="true"
                        type="string" xmlExtendInfo='{"xmlPath":{"path":["simpleData"]},"pathDirect":1,"keyPath":2,"valuePath":3,"attrName":"class","attrValue":"age"}'/>
                    <columnHead titleName="TCP" fieldName="TCP" required="true"
                        type="string" xmlExtendInfo='{"xmlPath":{"path":["simpleData"]},"pathDirect":1,"keyPath":2,"valuePath":3,"attrName":"name","attrValue":"TCP"}'/>
                    <columnHead titleName="name" fieldName="name" required="true"
                        type="string" xmlExtendInfo='{"xmlPath":{"path":[]},"pathDirect":0,"keyPath":1,"valuePath":2,"attrName":"name","attrValue":""}'/>
                </toParseTemplate>
            </toParseFile>
        </parsePoint>
		
        <!-- 通用解析文件配置 -->
        <files>
            <toParseFile name="myTestFile1" mode="single">
                <refTemplate name="myTemplate" />
            </toParseFile>
        </files>
		<!-- ERROR WITH myFile0，NO name with this <refToParseFile name="myFile0"/> -->
	</parseSystem>
</fileParse>
